name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * 5'

jobs:
  tests_js:
    runs-on: ubuntu-latest
    name: JS
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
